# Generated by Django 6.0.2 on 2026-03-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_round_trades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
